using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxGoob.Skills;

[GenerateTypedNameReferences]
public sealed partial class SkillTrainingWindow : FancyWindow
{
    public SkillTrainingWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
